### ISSUE TITLE
Feature Request: Dependent endpoints

### ISSUE THREAD

**Issue by TheSpad** [TwiN/gatus#109]
It would be very helpful to be able to decalre services as dependent on others and then at a minimum not alert for child services if the parent is down, and ideally suspend checks and flag them as unavailable rather than running checks against services that will always fail.

**Comment by TwiN** [comment]
I don't plan on implementing this, because in the future, I'd like to add support for "suites". 

A "suite" of tests would be like a list of endpoints that are executed in order, and each step would have a "clean up endpoint" if it fails. A suite is successful only if all endpoints are successful.

For instance, a suite could have the following steps:
1. Create an account
2. Login to the account
3. Call `/api/v1/users/me`

While this isn't exactly what you're looking for, I feel this would be able to achieve something similar enough.
