### ISSUE TITLE
Print Response Body of endpoints

### ISSUE THREAD

**Issue by mani9223-oss** [TwiN/gatus#244]
### Describe the feature request

It would be nice to show the Response Body of endpoints along with Response Time and status code.

**Comment by TwiN** [comment]
In the logs?

**Comment by mani9223-oss** [comment]
> In the logs?

![image](https://user-images.githubusercontent.com/60106299/152532377-bfca8c24-ade6-4eb1-a22e-9990c26ab131.png)
Please see the attached image. We can print after Conditions with title **Response Body**

**Comment by mani9223-oss** [comment]
Also I need to show the full URL here instead of just hostname. Is it possible?
![image](https://user-images.githubusercontent.com/60106299/152542655-6ea3663e-782a-4b34-b957-b545ac4c53d9.png)

**Comment by mani9223-oss** [comment]
@TwiN Can you please help me with the above requests?

**Comment by TwiN** [comment]
@mani9223-oss Unfortunately, neither of your questions are currently possible, nor do I plan on implementing them right now.

Printing a response body on the current UI would be messy, because some response bodies are very large while others are very small. The UI will be rewritten soon enough (whenever I'm done releasing https://gatus.io) and when that time comes, I may reconsider it, but at this time, I do not plan on making that available.

That being said, you can still kind of display the body on the UI on failure by using the `[BODY]` placeholder in a condition.

For instance, if you had the condition `[BODY].status == UP` but the response body was
```json
{
  "status": "DOWN"
}
```
the UI would display
```
X ~ [BODY].status (DOWN) == UP
```
Similarly, you could set the condition to `[BODY] == {\"status\":\"UP\"}`, and the UI would instead display
```
X ~ [BODY].status ({"status":"DOWN"}) == {"status":"UP"}
```

As for displaying the full URL instead of just the hostname, I'm not completely against the idea, but it'd require a breaking change on the API side and I don't really have the time for that right now.

**Comment by mani9223-oss** [comment]
I have implemented displaying the full endpoint URL in UI. Closing this issue.
