### ISSUE TITLE
Custom Telegram API Endpoint

### ISSUE THREAD

**Issue by undefined-moe** [TwiN/gatus#245]
### Describe the feature request

Allow `telegram.endpoint` setting.

### Why do you personally want this feature to be implemented?

In some countries, `api.telegram.org` is blocked, we have to use a custom endpoint (with proxy configured, or self-deployed telegram-bot-api server).

### How long have you been using this project?

~1year

**Comment by TwiN** [comment]
Fair enough! I would however prefer to have it be `alerting.telegram.api-url` instead of `alerting.telegram.endpoint` to avoid confusion. The default value would be `https://api.telegram.org/`.

Relevant code:
https://github.com/TwiN/gatus/blob/3f961a740874849b06adf5a778521b70dcaeb6c9/alerting/provider/telegram/telegram.go#L31
