### ISSUE TITLE
Allow for checking if json values are greater than or less than

### ISSUE THREAD

**Issue by JayFromProgramming** [TwiN/gatus#268]
### Describe the feature request

As of now you can check if a json value is equal to another value, but it does not appear to be possible to check if a json value is less than or greater than a value
![image](https://user-images.githubusercontent.com/46631427/159512207-e7ef852a-a870-4cfa-98e1-5aa552520dd6.png)
It'd be incredibly useful at least in my desired usecase to be able to check if a json value is less than or equal to lets say 50 as an example so `[BODY].data[0].temp < 65`  or `[BODY].data.load < 0.85` would be very useful. 

### Why do you personally want this feature to be implemented?

I'm setting my server nodes for high availability as I won't be onsite to monitor them and having automated early warning of issues with my node will go a long way in me being able to make sure they still stay up and health, so being able to get automated temperature alerts ect will be of great use. 

### How long have you been using this project?

about 6 months

**Comment by TwiN** [comment]
Hello @JayFromProgramming! 

In fact, what you're asking for should already be supported. There's even a test for it:
https://github.com/TwiN/gatus/blob/a81c81e42c80aae76c1aad4df5a3f4e1185c0b92/core/condition_test.go#L222-L226

That being said, I'm pretty sure it doesn't work for decimals, as the value is parsed to an integer rather than a float:
https://github.com/TwiN/gatus/blob/a81c81e42c80aae76c1aad4df5a3f4e1185c0b92/core/condition.go#L267-L280

**Comment by TwiN** [comment]
Since the feature you requested is partially supported and you haven't said anything for nearly two weeks, I'm going to close this, but feel free to re-open.
