### ISSUE TITLE
feat: Add configuration option to disable the GUI

### ISSUE THREAD

**Issue by dchidell** [TwiN/gatus#306]
Gatus provides excellent monitoring and alerting capabilities, however there are instances where the GUI is not required where heavy usage of the aforementioned features are used.

It would be great to have an option to simply entirely disable the GUI to save resources if an endpoint queries a very heavy GUI by accident.

**Comment by TwiN** [comment]
By disabling the GUI, do you mean disabling the web server for the UI? (e.g. https://status.twin.sh)

**Comment by dchidell** [comment]
Exactly - but keeping the API in tact.

**Comment by TwiN** [comment]
Hmm it shouldn't be much of a problem.

All you'd need to do is add a new configuration here: https://github.com/TwiN/gatus/blob/7daf2b5cac28201c33fc924a7533609f0eb6ee8e/config/ui/ui.go#L25-L31

something like `Disabled`, and then use that configuration here:
https://github.com/TwiN/gatus/blob/7daf2b5cac28201c33fc924a7533609f0eb6ee8e/controller/handler/spa.go#L11-L27

something like if ui.Disabled, then return 404 with an error message that says that the UI has been disabled.

---

That being said, it's not _really_ useful, because this is a single page application, which means that the html pages rendered are practically empty. You can see this yourself by navigating to `view-source:https://status.twin.sh/` on Chrome/Firefox, or by going on your Gatus instance's page and right clicking `View page source`.

of course, if you're talking about an application that can render JS, or an actual user, that's another story.

I guess the largest files that could be accidentally requested outside of the API would be the vendor & the app's file (e.g. https://status.twin.sh/js/chunk-vendors.js, https://status.twin.sh/js/app.js), but unless there's a _lot_ of requests, the resource utilization incurred from retrieving these two files is pretty small. 

If you're worried about users accessing the API for no reason, you could always configure auth. Something like [this](https://github.com/TwiN/gatus#basic) should do the trick, but you'll have to ensure that whatever application you have that calls the API can include basic auth in the request it sends as well.

**Comment by TwiN** [comment]
Unfortunately, I'm going to decline this feature.

The resources consumed by running the web server when there's no traffic is negligible, as for resources consumed due to users using the UI, there are many ways to prevent people from accessing the UI (e.g. don't expose the application publicly, set a port that isn't forwarded/accessible, enable auth as suggested above, etc.).

Regardless, thank you for creating an issue!
