### ISSUE TITLE
send alert message to lark failed

### ISSUE THREAD

**Issue by Little-Mo** [TwiN/gatus#413]
i tried to send alert message to lark robot, but it doesn't work

gatus configuration：
alerting:
  custom:
    url: "https://open.larksuite.com/open-apis/bot/v2/hook/xxxxxxxxxxxxxxxxxxxxxxxxxxx"
    method: "POST"
    data: {"msg_type":"text","content":{"text":"request example"}}
endpoints:
  - name: test
    group: core
    url: "https://test.com/abc"
    interval: 5s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].code == 1"
    alerts:
      - type: custom

gatus log:
[watchdog][handleAlertsToTrigger] Sending custom alert because alert for endpoint=graph.nhaccuatui.com with description='' has been TRIGGERED

**Comment by TwiN** [comment]
Your issue probably has to do with the fact that you're using `data` instead of `body`, which is not a custom parameter.

If you still have an issue, please create a new issue using [the relevant template](https://github.com/TwiN/gatus/issues/new/choose) (`Bug report`, in your case), and make sure to [format your configuration](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) properly as it's very difficult to read otherwise.
