### ISSUE TITLE
Unable to login to docker container of gatus

### ISSUE THREAD

**Issue by Subhasish5** [TwiN/gatus#483]
### Describe the feature request

Hi Team,

I downloaded the docker image of gatus to my local docker desktop : 
![image](https://github.com/TwiN/gatus/assets/46413003/d686983d-74ef-4aae-a64c-52be459a862d)
but when I trying to log into the container ; I am getting the below error : 

![image](https://github.com/TwiN/gatus/assets/46413003/45f18dff-c55f-4603-8c30-c698e2655989)

Please help me fix this and also please add the $PATH variable in the image so that it can be logged in.

Thanks and Regards,
Subhasish

**Comment by Subhasish5** [comment]
[Gatus_logs.txt](https://github.com/TwiN/gatus/files/11510263/Gatus_logs.txt)
[Gatus_logs_2.txt](https://github.com/TwiN/gatus/files/11510264/Gatus_logs_2.txt)
[Gatus.txt](https://github.com/TwiN/gatus/files/11510265/Gatus.txt)

Please find the logs attached for your reference

**Comment by TwiN** [comment]
This is being discussed elsewhere, so I will close this, but for future reference:


The Gatus Docker image is made to be lightweight, which is why there is no shell. You cannot open a shell inside on Gatus unless you create a custom Docker image with a shell. What you could do, however, is add a sidecar to your Gatus pod with the busybox image. You would then be able to open a shell in the Gatus pod from the busybox container.
