### ISSUE TITLE
Persist refresh interval on change

### ISSUE THREAD

**Issue by macmoritz** [TwiN/gatus#509]
### Describe the feature request

In the ui part of the YAML config I want to set the default refresh value of the frontend. 

### Why do you personally want this feature to be implemented?

I am to lazy to switch to the 10s refresh interval again and again, a preconfigured one would be nice.

**Comment by TwiN** [comment]
> I am to lazy to switch to the 10s refresh interval again and again, a preconfigured one would be nice.

It seems I accidentally used sessionStorage instead of localStorage on the UI

https://github.com/TwiN/gatus/blob/bde30b2efb82982e6b77592cc0c690760906e8d1/web/app/src/components/Settings.vue#L36

https://github.com/TwiN/gatus/blob/bde30b2efb82982e6b77592cc0c690760906e8d1/web/app/src/components/Settings.vue#L81
