### ISSUE TITLE
client.insecure Does Not Affect TLS/STARTTLS Checks

### ISSUE THREAD

**Issue by asimons04** [TwiN/gatus#541]
### Describe the bug

I am trying to monitor TLS endpoints that use certificates signed by an internal CA.  For the purposes of this monitor, TLS validation is not strictly necessary.  For HTTPS endpoints, setting `client.insecure` to `true` will prevent certificate validation errors from causing a failure response.  This doesn't seem to be honored for TLS/STARTTLS checks.

In the interim, I am just using TCP checks which are not able to provide additional useful information such as [CERTIFICATE_EXPIRATION]

### What do you see?

When doing a TLS or STARTTLS check, the `client.insecure` option does not seem to be honored and the checks fail if the cert is unable to be validated for any reason (no IP SAN, not trusted, etc)

### What do you expect to see?

When setting `client.insecure` to `true` for an endpoint, TLS validation for TLS/STARTTLS checks should be disabled to allow the check to complete.

### List the steps that must be taken to reproduce this issue

1. Configure an endpoint that uses a TLS check
2. Either use a target that has a self-signed cert or replace the hostname with its IP address (assuming the cert does not have an IP SAN)
3. Set `client.insecure` to `true` for that endpoint

The check will fail for one or more reasons related to TLS validation.

### Version

5.5.1

**Comment by TwiN** [comment]
@asimons04 I've never personally tested this case, but I did assume that the following would work for STARTTLS: https://github.com/TwiN/gatus/blob/225e6ac7ae122243b0f88047ee15071939a2e770/client/client.go#L128-L131

As for TLS, you're right in that I wouldn't expect `client.insecure` being set to `true` to change anything considering the code itself doesn't even take `client.insecure` into consideration: https://github.com/TwiN/gatus/blob/225e6ac7ae122243b0f88047ee15071939a2e770/client/client.go#L144-L155

Would you like to try fixing the issue, since you seem to be in a position where you can reproduce this issue locally?

**Comment by vax-r** [comment]
@TwiN @asimons04 
Can I try to solve it?
Seems that no one is fixing it right now?

**Comment by vax-r** [comment]
@TwiN @asimons04 
Hello, I've made some changes to fix the bug and create a PR for it.
Would you mind do the code review for me ?
Ofcourse when you guys have available time
Thank you so much!

**Comment by amai2012** [comment]
That's still to be released, isn't it?

**Comment by TwiN** [comment]
@amai2012 It hasn't been released as part of a tagged version yet, but you can use `latest` if you need it immediately.
Is there a specific reason why you need it now?
