### ISSUE TITLE
Infinite clicks are needed to see previous data

### ISSUE THREAD

**Issue by 221bshashank** [TwiN/gatus#595]
### Describe the bug

Suppose I have implemented to store my data in postgreSQL but to look into data maybe 1week ago through UI, I will have to do infinite clicks on the back button, is there any sort of pagination or search functionality to look into older data?

### What do you see?

A back button only 

### What do you expect to see?

Pagination or search functionality

### List the steps that must be taken to reproduce this issue

Connect to postgreSQL to store data

### Version

latest

**Comment by 221bshashank** [comment]
@TwiN pls have a look into this issue, I need to use this on enterprise level.

**Comment by TwiN** [comment]
This is not possible, because the maximum number of entries is hardcoded and only 5 pages of 20 entries each are displayed. In other words, there is a maximum of 5 pages at this time.

This may change in the future, but at least for now, there should be no cases where you change pages more than 4 times to reach the last page of results.
